/_:
  ros__parameters:
    dx: 10.0
    dy: 20.0
    map: hexagon
    max_timeout: 3
    use_sim_time: true
/_/send_gates:
  ros__parameters:
    x:
    - -7.690177004240538
    y:
    - -2.80073078514634
    yaw:
    - 3.6651914291880923
/_/send_obstacles:
  ros__parameters:
    max_size: 1.0
    min_size: 0.5
    n_obstacles: 3
    no_cylinders: true
    vect_dim_x:
    - 0.8820900964443035
    - 0.802409396759556
    - 0.6726381981491196
    vect_dim_y:
    - 0.7152027100269165
    - 0.8759215841988915
    - 0.6756395266940367
    vect_type:
    - box
    - box
    - box
    vect_x:
    - 2.6733033109968165
    - 2.5712760421601892
    - -4.870721177590422
    vect_y:
    - 7.712039493945973
    - 5.502010998812922
    - -7.154659328034796
    vect_yaw:
    - 2.760593949574428
    - 1.6006218002929504
    - -1.536793597154922
/_/send_timeout:
  ros__parameters:
    victims_timeout: 0
/_/send_victims:
  ros__parameters:
    max_weight: 500.0
    min_weight: 10.0
    vect_weight:
    - 349.0
    - 168.0
    - 74.0
    - 181.0
    vect_x:
    - -1.6781680751825623
    - -0.3790887536748855
    - -3.2211279966561666
    - -3.5177638643708473
    vect_y:
    - -7.315254464906474
    - -4.223742497437923
    - 0.25884327939871277
    - 2.426417927995381
    victims_activated: true
    victims_timeout: 0
