/_:
  ros__parameters:
    dx: 10.0
    dy: 20.0
    map: hexagon
    max_timeout: 3
    use_sim_time: true
/_/send_gates:
  ros__parameters:
    x:
    - -7.328255235746172
    y:
    - 3.427597676543762
    yaw:
    - 2.617993877991494
/_/send_obstacles:
  ros__parameters:
    max_size: 1.0
    min_size: 0.5
    n_obstacles: 5
    no_cylinders: true
    vect_dim_x:
    - 0.5296903321045965
    - 0.8872107246184375
    - 0.7352367758863061
    - 0.509559602026498
    - 0.6525279969503597
    vect_dim_y:
    - 0.6710171210714942
    - 0.624000650526854
    - 0.7421105761941482
    - 0.6913946542402845
    - 0.887722715944647
    vect_type:
    - box
    - box
    - box
    - box
    - box
    vect_x:
    - -4.222046306320628
    - 1.9421213317989068
    - -1.9646602075854034
    - 3.881895449963162
    - 1.0819399138996344
    vect_y:
    - 0.3686611115613747
    - -4.780784479630351
    - 1.2419542797533705
    - 2.4946054727535802
    - 3.0396391042894866
    vect_yaw:
    - 0.5165899747810982
    - -2.555252705929527
    - -1.257760978065227
    - 0.24123260888418407
    - -1.0323231661106949
/_/send_timeout:
  ros__parameters:
    victims_timeout: 60
/_/send_victims:
  ros__parameters:
    max_weight: 500.0
    min_weight: 10.0
    vect_weight:
    - 129.0
    - 162.0
    - 421.0
    - 143.0
    - 49.0
    - 243.0
    vect_x:
    - 3.608218494095672
    - 0.3559035002476252
    - 4.512203721589698
    - 0.45399618743871706
    - -0.9037836704759252
    - 4.232849599815772
    vect_y:
    - -6.775652171952366
    - -3.821117362987641
    - 4.482238944059034
    - -3.0751788711664663
    - 3.186615454363505
    - 5.112433452646826
    victims_activated: true
    victims_timeout: 60
