/_:
  ros__parameters:
    dx: 10.0
    dy: 20.0
    map: hexagon
    max_timeout: 3
    use_sim_time: true
/_/send_gates:
  ros__parameters:
    x:
    - -9.03539128149242
    y:
    - -0.47075130987903363
    yaw:
    - 3.6651914291880923
/_/send_obstacles:
  ros__parameters:
    max_size: 1.0
    min_size: 0.5
    n_obstacles: 3
    no_cylinders: true
    vect_dim_x:
    - 0.7442282333813128
    - 0.9072315209382401
    - 0.5661842283618659
    vect_dim_y:
    - 0.620620098835449
    - 0.7412858007044958
    - 0.6391233349346179
    vect_type:
    - box
    - box
    - box
    vect_x:
    - 0.6025838558629113
    - -2.3503603696854003
    - -4.43676220651375
    vect_y:
    - -4.2198806903624835
    - -3.7178487931649107
    - -7.43093652203161
    vect_yaw:
    - 1.5967059184515948
    - 1.6797002721006322
    - -2.7518057251453327
/_/send_timeout:
  ros__parameters:
    victims_timeout: 0
/_/send_victims:
  ros__parameters:
    max_weight: 500.0
    min_weight: 10.0
    vect_weight:
    - 380.0
    - 260.0
    - 465.0
    - 62.0
    vect_x:
    - 2.2468268532599467
    - -3.2695539168620558
    - -1.347942991243932
    - 0.03711037433797326
    vect_y:
    - 4.355714766903748
    - 6.644008682251364
    - 4.353511090157198
    - -2.004657875800868
    victims_activated: true
    victims_timeout: 0
