/_:
  ros__parameters:
    dx: 10.0
    dy: 20.0
    map: hexagon
    max_timeout: 3
    use_sim_time: true
/_/send_gates:
  ros__parameters:
    x:
    - -8.05652077414559
    y:
    - -2.166204762634467
    yaw:
    - 3.6651914291880923
/_/send_obstacles:
  ros__parameters:
    max_size: 1.0
    min_size: 0.5
    n_obstacles: 5
    no_cylinders: true
    vect_dim_x:
    - 0.7601659658735282
    - 0.9026280857252996
    - 0.7149811816259815
    - 0.641604279022298
    - 0.6243726903820752
    vect_dim_y:
    - 0.6512869703170725
    - 0.6786665882586251
    - 0.7370962269871664
    - 0.8910292619878357
    - 0.6255898748783957
    vect_type:
    - box
    - box
    - box
    - box
    - box
    vect_x:
    - -0.07712331674524808
    - 1.8268465844279387
    - -2.7041422748510238
    - -4.91773902240308
    - 0.7150073130396848
    vect_y:
    - 7.934080565943098
    - 5.226839827901841
    - 5.503728082557984
    - 2.121390756204086
    - -6.64884888785344
    vect_yaw:
    - -2.632747335177477
    - 1.475012406219185
    - -1.3443630283483377
    - -2.2662167272495415
    - 2.89227227299628
/_/send_timeout:
  ros__parameters:
    victims_timeout: 20
/_/send_victims:
  ros__parameters:
    max_weight: 500.0
    min_weight: 10.0
    vect_weight:
    - 263.0
    - 219.0
    - 497.0
    - 116.0
    - 462.0
    - 125.0
    vect_x:
    - -3.067180063198567
    - 0.7481212821247416
    - 3.0795943550925227
    - -3.246375270027909
    - -1.349158777084527
    - 2.9805204938520973
    vect_y:
    - 7.622108900314501
    - -1.4307890516816464
    - -7.228976633952171
    - 0.5256939513906129
    - 3.2515361168149077
    - -5.603138583332532
    victims_activated: true
    victims_timeout: 20
